version: "3.9"

services:
  pg:
    image: postgres:16
    container_name: accurate_pg
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-accurate} -d ${POSTGRES_DB:-accurate}"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  pgdata: {}
